### ISSUE TITLE
[severus] Kenku enters in discord but sound doesnt come out.

### ISSUE THREAD

**Issue by mthehh** [owlbear-rodeo/kenku-fm#80]
**Describe the bug**
Kenku enters the discord but no sounds comes out. if I select my PC it works.
I have already tried to change the version and reinstall it, as well as create a new bot.
It was working fine last week, this just started out of nowhere. 
Any suggestions on how to fix it?

Windows 10 pro
 - Version v1.3.1

![imagem_2023-03-22_211948509](https://user-images.githubusercontent.com/126734355/227067378-a51b005b-0312-4666-a2d9-7d8f464f4b4c.png)

**Comment by nthouliss** [comment]
We've had others report a similar issue but how they've managed to resolve it differs. Once person just restarted their computer, another swapped their Discord output. Have you also tried a restart and a cache clear (which is available through the settings)?

**Comment by mthehh** [comment]
Yes, I have cleared the cache. Reinstalled the app. Reinstalled my PC. Also tried other discord servers. Unfortunately nothing so far :C
Even tried older versions to fix it.

**Comment by nthouliss** [comment]
The only other I could think of to suggest would be to check that you have allowed Kenku FM access in Firewall settings (for private access) but even when I disabled access on my end I wasn't able to reproduce this bug. 

We can keep trying but if you want to get this resolved sooner then I'd suggest pulling the source code and seeing what errors crop up. It's very possible that we're swallowing the error.

**Comment by mthehh** [comment]
How would I do that? "pulling the source code and seeing what errors crop up."

**Comment by nthouliss** [comment]
I'd only recommend it if you have some development experience. If not, we'll keep chipping away on our end :)

**Comment by mthehh** [comment]
Well, kenku is one of the tools I use in my work so I really am open to try. I am used to modding games and stuff but usually I just follow steps. I really need kenku to work :C It is one of the most important tools I use.

**Comment by nthouliss** [comment]
You would have to go through our README to get a general overview on how the application works, as well as some knowledge of Javascript and possibly Rust. For the moment, in Kenku FM could you visit `chrome://webrtc-internals/` and then try to send audio through DIscord, afterwards go back to `chrome://webrtc-internals/` and then click `Create Dump` at the top and then click `Download the PeerConnection updates and stats data` with `Compress result` ticked. 
It will save a file to your local file system. Then email that file to us at support@owlbear.rodeo 

The `chrome://webrtc-internals/` option to Create Dump will look like this

![Screen Shot 2023-03-23 at 4 26 26 pm](https://user-images.githubusercontent.com/53867736/227112509-e2f0a64a-fee2-438d-bded-259817c8110c.png)

**Comment by mthehh** [comment]
Okay, I will send that file to you guys. The error seems a bit different with the new version. 
First it connects to discord, I send audio and it doesnt work. Then I disconect from the output and try to reconnect and it doesnt connect anymore. I get another message now.
![image](https://user-images.githubusercontent.com/126734355/227280977-446fb76d-217d-4ad6-b08a-eab84693b840.png)

**Comment by nthouliss** [comment]
Okay, well this narrows down the issue at least. It seems that WebRTC isn't running for you (the audio stream), I'm not sure why this could be at the moment but we'll keep digging on our end.

**Comment by mthehh** [comment]
Thank you so much, that gives me hope.
Your app is amazing I really need it :D

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Não
contém vírus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui., 23 de mar. de 2023 às 21:23, Nicola Thouliss <
***@***.***> escreveu:

**Comment by nthouliss** [comment]
@mthehh could you test the version that I've put in releases under 1.3.3-test?

https://github.com/owlbear-rodeo/kenku-fm/releases/tag/1.3.3-test

**Comment by mthehh** [comment]
Okay, I have found out what it is happening but I don't know why. 
If I disable Avast the sound comes, the moment I enable it stops working. 
I have already allowed Kenku in it's settings but for some reason it just blocks it.

**Comment by mthehh** [comment]
It seems it is the firewall,  that's why other people might be having the same issue. Even though I already allowed it in the settings.

**Comment by mthehh** [comment]
Here I reproduce the bug
https://user-images.githubusercontent.com/126734355/227472268-56e65ddb-76f2-45ed-9a1a-c73517403587.mp4

**Comment by mthehh** [comment]
Found something else. 
It seems that changing the "I trust this network" allows the sound to come through.
https://user-images.githubusercontent.com/126734355/227473284-be4815a2-2c13-49c2-a67b-fb196300d3a7.mp4

**Comment by nthouliss** [comment]
Thanks for that @mthehh 

Could you try that package I put in the releases with the firewall block enabled?

**Comment by nthouliss** [comment]
I had a go of it with Avast and couldn't quite get the reproduction you have. It would sometimes block with Firewall enabled and then other times not. I would appreciate you seeing if the version I dropped in the releases works correctly with Firewall on :)

**Comment by mthehh** [comment]
That version works with the firewall on, but only if the network is private
not public. For some reason if I select "I don't trust this network." The
app doesn't work in either of the versions.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Não
contém vírus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nthouliss** [comment]
This should be resolved in v1.4.0. I'll keep it open to track it as part of our experimental version for rust/severus

**Comment by kleelue** [comment]
With Version 1.4.0 experimental we still have the problem, that no sound is coming out. We reverted to 1.4.0 w/o experimental, and it works again. Please be careful to not get this error in again. (:

**Comment by nthouliss** [comment]
> With Version 1.4.0 experimental we still have the problem, that no sound is coming out. We reverted to 1.4.0 w/o experimental, and it works again. Please be careful to not get this error in again. (:

This issue is still open and labeled with severus indicating that it's still an issue with experimental. It's never had a patch to solve this for everyone.

**Comment by ProfDogg** [comment]
Hi!  Clueless guy here...  I'm having the same issues as above and have not been able to resolve it.  No firewall issue that I can detect...  I've redownloaded Kenku and reset my token and reloaded it.  Anything I can do to help ID the issue?

**Comment by mthehh** [comment]
For me it was my anti virus, Avast. I had to change the network from private to public to work.

**Comment by st-fankl-in** [comment]
Running 1.4.0-experimental on linux, running into this (or a similar?) issue too.
What I found is, if kenku joins the discord channel first while no other client is present and others join after kenku sound output works. If I (or another client) joins first and kenku joins later it doesn't play any sound. It works again when everybody leaves the channel, Kenku leaves (e.g. by switching the output to this computer), joins again before any other participant joins the audio channel.
Maybe this helps as workaround for some and/or debugging the issue further.

**Comment by ProfDogg** [comment]
> 

That makes sense.  I hadn't tested the sequence like you described but that fits what I observed as well.  Next time I'm on I'll test that.

**Comment by nthouliss** [comment]
@st-fankl-in we were able to reproduce this. It should be patched in the latest version of [experimental](https://github.com/owlbear-rodeo/kenku-fm/releases/tag/v1.4.1-experimental). It should auto-update (you can check your version in the settings) but if you want to be sure you can always download it again.

**Comment by st-fankl-in** [comment]
@nthouliss do you know if this was the initial issue and my comment helped to debug it, or was this unrelated and I should have opened a new issue?

**Comment by nthouliss** [comment]
I'm not sure exactly if this was the initial issue, it may have been a mix of firewall and what you reported. We haven't ever been able to reproduce reliably with firewall changes, so it's possible that it was what you reported all along (which was super helpful btw). If I get confirmation from @ProfDogg that they're all good I'll close this, I can always reopen if someone else reports again.

**Comment by ProfDogg** [comment]
I'll be running a live game tomorrow when I get back home so I'll have results for you by Saturday.

**Comment by ProfDogg** [comment]
It worked well.  I had to go back and forth with dropping players from Discord and readding them but it worked in all circumstances.  About 2 hours in, the sound did drop but came back later.  I assume that was some connectivity issue but the initial problem seems to have resolved.
